### ISSUE TITLE
L1 Mastering Font checklist

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/puppies-play#3]
### L1 Mastering Font checklist

**Diacritics**
- [x] Inspect the font and choose the best version of the diacritics (in terms of balance, weight, size, contrast) and move them to comb mark.
- [x] Adjust left and right sidebearings of all the comb marks to 0.
- [x] Work on the selected diacritics to ensure the balance among all marks (contrast, weight, size, stroke or others)
- [x] Adjust position, weight, or outlines of the diacritics if needed to, without changing the design of them by using glyphs app locked guidelines.
- [x] Test the comb marks by inspecting all of them in context (right click and choose all glyphs using this component).
- [x] Inspect and balance the below marks (size, weight, balance) e.g. `ogonek` `cedilla` to avoid huge marks
- [x] Delete the legacy marks and add them back so they are made from comb marks.
- [x] Create comb.case marks by making them less tall and less narrow while keeping them at the same weight. (Preferable at the height they are intended to use, to be able to inspect them at their context)
- [x] Create the Vietnamese mark.
- [x] Make component glyphs for all of the font.
- [x] Adjust the anchor position.
- [x] Run the automatic glyphsapp command: update gyph info

**Glyphs & Outlines**
- [x] Create the missing glyphs needed
- [x] Run the automatic glyphsapp command: Add extremes, Correct outlines direction, Remove PS Hint.
- [x] Check kerning and spacing by using the txt files. Fix any kerning and spacing errors if needed for the most common kerning pairs.
- [x] Run the automatic glyphsapp command: `Resolve all metrics` to update the metrics in all the font.
- [x] Check everything once again by going glyph by glyph.
- [x] Run the automatic glyphsapp `Update Glyph Info` command to avoid bad names issues
- [x] Run the automatic glyphsapp `Convert to cubic` command to avoid qcurves

**OT Features**
- [x] Check OpenType features and see if all listed are valid, e.g. if `.fina` glyphs are actually ending shapes or ss are not repeated under different names.
- [x] Inspect if Stylistic Sets have the right name or rename .001 etc... glyphs and generate the automatic OpenType code.
- [x] Check if there is a stylistic set that would correspond to `SmallCaps` feature instead and change it.
- [x] Check if the OpenType code has any error.
- [x] Hit the `update` & `compile` buttons to check everything is working well.

**Testing changes**
- [x] Inspect the font created by the CI GHA to check production errors. If the action isn't included yet in the repo, export and test the font using Glyphs.
- [x] Check the before and after font using `gen-html diff` if needed (for update font cases)
- [x] Check the font on `gen-html proof` to see if it's working well on web. Use the `--imgs` flag to produce images.
- [x] Commit and make PR using images.

**Comment by vv-monsalve** [comment]
Hi @crystaltype,

While working on the last round of QA for Puppies Play, I found some issues that were not covered.
We've talked about them in the past, although some were not listed in the previous checklist (above). I understand some of them are more tricky to catch than others, but as the ideal would be to avoid them, that's why I'm reporting here.

* Missing extreme points, that lead to not rounded coordinates
<img width="621" alt="Screen Shot 2021-10-12 at 19 58 35" src="https://user-images.githubusercontent.com/48698976/137228617-2fead5ef-4bd2-4057-bef9-909fa4092c91.png">

* Bad positions for some punctuation
<img width="1268" alt="Screen Shot 2021-10-12 at 22 03 29" src="https://user-images.githubusercontent.com/48698976/137228619-f7d2ce26-6e48-4441-bee5-dddc23135368.png">
<img width="903" alt="Screen Shot 2021-10-12 at 22 10 24" src="https://user-images.githubusercontent.com/48698976/137228620-9b781c28-9fe7-46a8-8681-dfda4f1b8a6a.png">

* Wrong outlines order 
<img width="614" alt="Screen Shot 2021-10-12 at 20 04 38" src="https://user-images.githubusercontent.com/48698976/137228618-4342e8d6-a1a4-4e9f-8616-c363acb023a3.png">

**Comment by crystaltype** [comment]
@vv-monsalve Thank you. Maybe It could be a good idea to add "Check spacing/position of punctuation, especially @, double/single quotes, and question marks" to the mastering checklist? They're often problematic, it would help me to not forget to check them.

Also when I  use the correct path directions command, in some cases it leads to the shape of the glyph (especially the counter) being wrongly filled. In that case, should I manually invert path directions? Or is there another way to fix it?

**Comment by vv-monsalve** [comment]
> Maybe It could be a good idea to add "Check spacing/position of punctuation

Yes, it is already included on the latest version, next to the `@` 

> In that case, should I manually invert path directions?

I've been doing it manually, since the source of this is usually that command. However, perhaps you could check if there is a good plugging/script for it ;)
